spring.application.name=auth_service

# Port untuk auth-user-service
server.port=8021

# Konfigurasi Database PostgreSQL db_cuanflow
spring.datasource.url=jdbc:postgresql://localhost:5432/db_cuanflow
spring.datasource.username=postgres
spring.datasource.password=ines123

# JPA Properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
