spring.application.name=auth_service

# Port untuk auth-user-service
server.port=8021

# Konfigurasi Database PostgreSQL db_cuanflow
spring.datasource.url=jdbc:postgresql://localhost:5432/db_cuanflow
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password_postgresql}

# JPA Properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret
jwt.secret=${JWT_SECRET:SecretKeyCuanFlowS1AkuntansiYangSangatPanjangDanAman123!}
