-- =========================================================
-- CUANFLOW — PERSONAL FINANCE MANAGEMENT SYSTEM
-- DDL DATABASE SCHEMA (PostgreSQL)
-- Program Studi S1 Akuntansi & Sistem Informasi
-- =========================================================

-- =========================================================
-- 1. ENUM TYPES
-- =========================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE user_role AS ENUM ('USER', 'ADMIN');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'transaction_type') THEN
        CREATE TYPE transaction_type AS ENUM ('INCOME', 'EXPENSE');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_method') THEN
        CREATE TYPE payment_method AS ENUM ('CASH', 'BANK_TRANSFER', 'E_WALLET', 'DEBIT_CARD', 'CREDIT_CARD', 'OTHER');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'budget_status') THEN
        CREATE TYPE budget_status AS ENUM ('ACTIVE', 'COMPLETED', 'CANCELLED');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'goal_status') THEN
        CREATE TYPE goal_status AS ENUM ('ACTIVE', 'COMPLETED', 'CANCELLED');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_type') THEN
        CREATE TYPE notification_type AS ENUM ('BUDGET_ALERT', 'GOAL_REMINDER', 'TRANSACTION_REMINDER', 'SYSTEM', 'INFO');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'category_type') THEN
        CREATE TYPE category_type AS ENUM ('INCOME', 'EXPENSE');
    END IF;
END $$;

-- =========================================================
-- 2. TABEL USERS (Pengguna Sistem)
-- =========================================================
CREATE TABLE IF NOT EXISTS users (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(150) UNIQUE,
    password VARCHAR(255) NOT NULL,
    role user_role NOT NULL DEFAULT 'USER',
    phone VARCHAR(20),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    reset_password_token VARCHAR(100),
    reset_password_token_expiry TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
);

-- =========================================================
-- 3. TABEL PROFILES (Biodata & Profil Pengguna)
-- =========================================================
CREATE TABLE IF NOT EXISTS profiles (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT4 NOT NULL UNIQUE,
    avatar_url TEXT,
    date_of_birth DATE,
    gender VARCHAR(20),
    address TEXT,
    occupation VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_profiles_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- =========================================================
-- 4. TABEL CATEGORIES (Kategori Transaksi)
-- =========================================================
CREATE TABLE IF NOT EXISTS categories (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT4,
    name VARCHAR(100) NOT NULL,
    type category_type NOT NULL,
    description TEXT,
    icon VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
);

-- =========================================================
-- 5. TABEL TRANSACTIONS (Buku Kas & Catatan Keuangan)
-- =========================================================
CREATE TABLE IF NOT EXISTS transactions (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT4 NOT NULL,
    category_id INT4 NOT NULL,
    type transaction_type NOT NULL,
    amount NUMERIC(15,2) NOT NULL,
    title VARCHAR(150) NOT NULL,
    description TEXT,
    transaction_date DATE NOT NULL,
    payment_method payment_method NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,

    CONSTRAINT chk_transaction_amount
        CHECK (amount > 0),

    CONSTRAINT fk_transactions_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_transactions_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

-- =========================================================
-- 6. TABEL BUDGETS (Pagu Anggaran Bulanan)
-- =========================================================
CREATE TABLE IF NOT EXISTS budgets (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT4 NOT NULL,
    category_id INT4,
    name VARCHAR(150) NOT NULL,
    amount NUMERIC(15,2) NOT NULL,
    month INT4 DEFAULT 8,
    year INT4 DEFAULT 2024,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    alert_percentage INTEGER NOT NULL DEFAULT 80,
    alert_threshold INTEGER DEFAULT 80,
    status budget_status NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_budget_amount
        CHECK (amount > 0),

    CONSTRAINT chk_budget_date
        CHECK (end_date >= start_date),

    CONSTRAINT chk_budget_alert
        CHECK (
            alert_percentage >= 0
            AND alert_percentage <= 100
        ),

    CONSTRAINT fk_budgets_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

-- =========================================================
-- 7. TABEL FINANCIAL_GOALS (Target Tabungan / Finansial)
-- =========================================================
CREATE TABLE IF NOT EXISTS financial_goals (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT4 NOT NULL,
    name VARCHAR(150) NOT NULL,
    target_amount NUMERIC(15,2) NOT NULL,
    current_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
    target_date DATE,
    description TEXT,
    status goal_status NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_goal_target_amount
        CHECK (target_amount > 0),

    CONSTRAINT chk_goal_current_amount
        CHECK (
            current_amount >= 0
            AND current_amount <= target_amount
        ),

    CONSTRAINT fk_financial_goals_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

-- =========================================================
-- 8. TABEL NOTIFICATIONS (Notifikasi Sistem & Pengingat)
-- =========================================================
CREATE TABLE IF NOT EXISTS notifications (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT4 NOT NULL,
    title VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    type notification_type NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    scheduled_at TIMESTAMP NULL,
    sent_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- =========================================================
-- 9. TABEL ATTACHMENTS (Bukti Bayar / Struk Transaksi)
-- =========================================================
CREATE TABLE IF NOT EXISTS attachments (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id INT4 NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_url VARCHAR(500) NOT NULL,
    file_type VARCHAR(50) NOT NULL,
    file_size BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_attachment_file_size
        CHECK (file_size > 0),

    CONSTRAINT fk_attachments_transaction
        FOREIGN KEY (transaction_id)
        REFERENCES transactions(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- =========================================================
-- 10. TABEL TAGS (Label Kustom Transaksi)
-- =========================================================
CREATE TABLE IF NOT EXISTS tags (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    user_id INT4 NOT NULL,
    
    CONSTRAINT fk_tags_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- =========================================================
-- 11. TABEL TRANSACTION_TAGS (Junction Transaksi <-> Tag)
-- =========================================================
CREATE TABLE IF NOT EXISTS transaction_tags (
    transaction_id INT4 NOT NULL,
    tag_id INT4 NOT NULL,

    PRIMARY KEY (transaction_id, tag_id),

    CONSTRAINT fk_transaction_tags_transaction
        FOREIGN KEY (transaction_id)
        REFERENCES transactions(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_transaction_tags_tag
        FOREIGN KEY (tag_id)
        REFERENCES tags(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- =========================================================
-- 12. INDEXES (Optimasi Kinerja Query Pencarian & Filter)
-- =========================================================
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_category_id ON transactions(category_id);
CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(transaction_date);
CREATE INDEX IF NOT EXISTS idx_transactions_type ON transactions(type);
CREATE INDEX IF NOT EXISTS idx_budgets_user_id ON budgets(user_id);
CREATE INDEX IF NOT EXISTS idx_budgets_status ON budgets(status);
CREATE INDEX IF NOT EXISTS idx_financial_goals_user_id ON financial_goals(user_id);
CREATE INDEX IF NOT EXISTS idx_financial_goals_status ON financial_goals(status);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_attachments_transaction_id ON attachments(transaction_id);
CREATE INDEX IF NOT EXISTS idx_tags_user_id ON tags(user_id);
CREATE INDEX IF NOT EXISTS idx_transaction_tags_trx_id ON transaction_tags(transaction_id);
