spring.application.name=gateway_service

# Port API Gateway
server.port=8024

# routing untuk Auth Service
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8021
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/authSvc/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/authSvc/(?<segment>.*), /${segment}

# routing untuk Finance Service
spring.cloud.gateway.server.webflux.routes[1].id=finance-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8022
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/financeSvc/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/financeSvc/(?<segment>.*), /${segment}

# routing untuk Notification Service
spring.cloud.gateway.server.webflux.routes[2].id=notification-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8023
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/notifSvc/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=RewritePath=/notifSvc/(?<segment>.*), /${segment}

# rate limiting (maksimal 5 request per 30 detik)
max_requests=5
time_window_seconds=30
